name: Tag and Deploy

on:
  push:
    branches:
      - 'main'

permissions:
  packages: write
  contents: write
  actions: read

jobs:
  determine-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Determine next tag
        id: tag
        run: |
          current_month=$(date +'%Y.%m')
          release_count=$(git tag -l "${current_month}.*" | wc -l | tr -d ' ')
          release_number=$((release_count + 1))
          echo "::set-output name=tag::${current_month}.${release_number}"

  create-tag:
    needs: determine-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create and push tag
        run: |
          git tag ${{ needs.determine-tag.outputs.tag }}
          git push origin ${{ needs.determine-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}