name: Tag and Deploy

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new release'
        required: true
        default: 'false'
        type: boolean
      version_number:
        description: 'Version number (Semantic Versioning)'
        required: true
        type: string
      branch:
        description: 'Branch to deploy'
        required: true
        type: choice
        options:
          - main
          - development
          - feature/**
          - release/**

permissions:
  packages: write
  contents: write
  actions: read

jobs:
  determine-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: 'true'

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Validate version number
        id: validate_version
        run: |
          if ! [[ "${{ github.event.inputs.version_number }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version number. Must follow Semantic Versioning (e.g., 1.0.0)."
            exit 1
          fi

      - name: Determine next tag
        id: tag
        run: |
          echo "::set-output name=tag::${{ github.event.inputs.version_number }}"

  create-tag:
    needs: determine-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create and push tag
        run: |
          git tag ${{ needs.determine-tag.outputs.tag }}
          git push origin ${{ needs.determine-tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ```